/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Arial Unicode MS16.c                                  *
* Font:        Arial Unicode MS                                      *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        2699 - 2699                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArialUnicodeMS16;

/* Start of unicode area <Miscellaneous Dingbats> */
GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_2660[ 20] = { /* code 2660, BLACK SPADE SUIT */
  ____XX__,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXXXXXX,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  _XXXXXXX,X_______,
  ____XX__,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_2661[ 22] = { /* code 2661, WHITE HEART SUIT */
  _XXXX_XX,XX______,
  XXX_XXX_,XXX_____,
  XX__XX__,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  _XX_____,XX______,
  __XX___X,X_______,
  ___XX_XX,________,
  ___XX_XX,________,
  ____XXX_,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_2662[ 18] = { /* code 2662, WHITE DIAMOND SUIT */
  ____XX__,________,
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  XX______,XX______,
  _XX____X,X_______,
  __XX__XX,________,
  ___XXXX_,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_2663[ 20] = { /* code 2663, BLACK CLUB SUIT */
  ____XXX_,________,
  ___XXXXX,________,
  ___XXXXX,________,
  _XXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  ____XXX_,________,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_2664[ 22] = { /* code 2664, WHITE SPADE SUIT */
  ____XX__,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  XX______,XX______,
  XX_XXXX_,XX______,
  XX_XXXX_,XX______,
  _XXXXXXX,X_______,
  ___XXXX_,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_2665[ 20] = { /* code 2665, BLACK HEART SUIT */
  _XXXXXXX,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_2666[ 20] = { /* code 2666, BLACK DIAMOND SUIT */
  ___XX___,________,
  ___XXX__,________,
  __XXXXX_,________,
  _XXXXXXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________,
  ___XXX__,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_2667[ 22] = { /* code 2667, WHITE CLUB SUIT */
  ____XXXX,________,
  ___XXXXX,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  _XXXX__X,XXX_____,
  XX______,__XX____,
  XX__XXXX,__XX____,
  XX__XXXX,__XX____,
  _XXXXX_X,XXX_____,
  ____XXXX,________,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_2668[ 18] = { /* code 2668, HOT SPRINGS */
  _____XX_,________,
  ___XXX_X,X_______,
  __XXXXXX,________,
  __XXXXXX,________,
  _XXXXXXX,XXX_____,
  XX_XXXXX,X_XX____,
  XX_XXXXX,X_XX____,
  _XX_____,_XX_____,
  __XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_2669[ 10] = { /* code 2669, QUARTER NOTE */
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  _XXXX___,
  XXXXX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_266A[ 11] = { /* code 266A, EIGHTH NOTE */
  ___XX___,
  ___XX___,
  ___XXXX_,
  ___XXXXX,
  ___XX_XX,
  ___XX_XX,
  ___XX_XX,
  ___XX___,
  _XXXX___,
  XXXXX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_266C[ 24] = { /* code 266C, BEAMED SIXTEENTH NOTES */
  _____XXX,XX______,
  ___XXXX_,XX______,
  ___XX_XX,XX______,
  ___XXXX_,XX______,
  ___XX___,XX______,
  ___XX___,XX______,
  ___XX___,XX______,
  ___XX_XX,XX______,
  _XXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,X_______,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_266D[ 10] = { /* code 266D, MUSIC FLAT SIGN */
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XXXXX___,
  XX_XX___,
  XXXX____,
  XXX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS16_266F[ 10] = { /* code 266F, MUSIC SHARP SIGN */
  ____XX__,
  _XX_XX__,
  _XXXXXX_,
  XXXXXX__,
  _XX_XX__,
  _XX_XX__,
  _XXXXXX_,
  XXXXXX__,
  _XX_XX__,
  _XX_____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontArialUnicodeMS16_CharInfo[14] = {
   {  10,  10,   1,   3,  11, acGUI_FontArialUnicodeMS16_2660 } /* code 2660, BLACK SPADE SUIT */
  ,{  11,  11,   1,   3,  11, acGUI_FontArialUnicodeMS16_2661 } /* code 2661, WHITE HEART SUIT */
  ,{  10,   9,   0,   4,  10, acGUI_FontArialUnicodeMS16_2662 } /* code 2662, WHITE DIAMOND SUIT */
  ,{  11,  10,   1,   3,  12, acGUI_FontArialUnicodeMS16_2663 } /* code 2663, BLACK CLUB SUIT */
  ,{  10,  11,   1,   3,  11, acGUI_FontArialUnicodeMS16_2664 } /* code 2664, WHITE SPADE SUIT */
  ,{  10,  10,   1,   3,  11, acGUI_FontArialUnicodeMS16_2665 } /* code 2665, BLACK HEART SUIT */
  ,{   9,  10,   1,   3,  10, acGUI_FontArialUnicodeMS16_2666 } /* code 2666, BLACK DIAMOND SUIT */
  ,{  12,  11,   1,   3,  12, acGUI_FontArialUnicodeMS16_2667 } /* code 2667, WHITE CLUB SUIT */
  ,{  12,   9,   1,   4,  13, acGUI_FontArialUnicodeMS16_2668 } /* code 2668, HOT SPRINGS */
  ,{   5,  10,   1,   3,   7, acGUI_FontArialUnicodeMS16_2669 } /* code 2669, QUARTER NOTE */
  ,{   8,  11,   1,   2,   9, acGUI_FontArialUnicodeMS16_266A } /* code 266A, EIGHTH NOTE */
  ,{  10,  12,   1,   2,  12, acGUI_FontArialUnicodeMS16_266C } /* code 266C, BEAMED SIXTEENTH NOTES */
  ,{   5,  10,   2,   3,   7, acGUI_FontArialUnicodeMS16_266D } /* code 266D, MUSIC FLAT SIGN */
  ,{   7,  10,   1,   3,   7, acGUI_FontArialUnicodeMS16_266F } /* code 266F, MUSIC SHARP SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArialUnicodeMS16_Prop3 = {
   0x266F /* first character */
  ,0x266F /* last character  */
  ,&GUI_FontArialUnicodeMS16_CharInfo[ 13] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArialUnicodeMS16_Prop2 = {
   0x266C /* first character */
  ,0x266D /* last character  */
  ,&GUI_FontArialUnicodeMS16_CharInfo[ 11] /* address of first character */
  ,&GUI_FontArialUnicodeMS16_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArialUnicodeMS16_Prop1 = {
   0x2660 /* first character */
  ,0x266A /* last character  */
  ,&GUI_FontArialUnicodeMS16_CharInfo[  0] /* address of first character */
  ,&GUI_FontArialUnicodeMS16_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontArialUnicodeMS16 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontArialUnicodeMS16_Prop1}
  ,13 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,10 /* Height of capital characters */
};

