/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FreeSerif16.c                                         *
* Font:        FreeSerif                                             *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x2699 (9881)                                 *
* Character disabled:  0x2699 (9881)                                 *
* Character enabled:   0x2699 (9881)                                 *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFreeSerif16;

/* Start of unicode area <Miscellaneous Dingbats> */
GUI_CONST_STORAGE unsigned char acGUI_FontFreeSerif16_2699[ 20] = { /* code 2699, GEAR */
  ___X__X_,________,
  ___XXXX_,________,
  __X____X,________,
  XX______,XX______,
  _X__XX__,X_______,
  _X__XX__,X_______,
  XX______,XX______,
  __X____X,________,
  ___XXXX_,________,
  ___X__X_,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFreeSerif16_CharInfo[1] = {
   {  10,  10,   0,   3,  11, acGUI_FontFreeSerif16_2699 } /* code 2699, GEAR */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFreeSerif16_Prop1 = {
   0x2699 /* first character */
  ,0x2699 /* last character  */
  ,&GUI_FontFreeSerif16_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFreeSerif16 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFreeSerif16_Prop1}
  ,12 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,9 /* Height of capital characters */
};

