/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "cable_main.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_TEXT_1    (GUI_ID_USER + 0x02)
#define ID_TEXT_2    (GUI_ID_USER + 0x03)
#define ID_TEXT_3    (GUI_ID_USER + 0x04)
#define ID_TEXT_4    (GUI_ID_USER + 0x05)
#define ID_SPINBOX_0    (GUI_ID_USER + 0x06)
#define ID_SPINBOX_1    (GUI_ID_USER + 0x07)
#define ID_SPINBOX_2    (GUI_ID_USER + 0x08)
#define ID_SPINBOX_3    (GUI_ID_USER + 0x09)
#define ID_SPINBOX_4    (GUI_ID_USER + 0x0A)
#define ID_CHECKBOX_0    (GUI_ID_USER + 0x0B)
#define ID_BUTTON_0    (GUI_ID_USER + 0x0C)
#define ID_BUTTON_1    (GUI_ID_USER + 0x0D)
#define ID_TEXT_5    (GUI_ID_USER + 0x0E)
#define ID_SPINBOX_5    (GUI_ID_USER + 0x0F)
#define ID_TEXT_6    (GUI_ID_USER + 0x10)
#define ID_SPINBOX_6    (GUI_ID_USER + 0x11)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Settings", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Error Margin %", ID_TEXT_0, 10, 16, 132, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Sheild Wire Error Margin", ID_TEXT_1, 10, 43, 132, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Sheild-Sheild Error Margin", ID_TEXT_2, 10, 70, 132, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ADC Switch Delay (us)", ID_TEXT_3, 10, 95, 134, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Wire Switch Delay (us)", ID_TEXT_4, 10, 122, 132, 20, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_0, 158, 11, 55, 26, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_1, 158, 38, 55, 26, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_2, 158, 65, 55, 26, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_3, 158, 92, 55, 26, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_4, 158, 119, 55, 26, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 12, 220, 130, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Touch Calibration", ID_BUTTON_0, 14, 268, 106, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Exit", ID_BUTTON_1, 136, 268, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Calib Add : 1000 is 0 mohm", ID_TEXT_5, 10, 149, 134, 20, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_5, 150, 146, 63, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Calibration Slop (%%)", ID_TEXT_6, 10, 176, 134, 20, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_6, 150, 173, 63, 26, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
int calc_step(int t){
	return 1 + t / 10;
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  int t;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "Check Bidirectional");
    // USER START (Optionally insert additional code for further widget initialization)
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    SPINBOX_SetRange( hItem, 1, 999 );
    t = nvrom_data.wire_wire_margin;
    SPINBOX_SetValue( hItem, t);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
    SPINBOX_SetRange( hItem, 1, 999 );
    t = nvrom_data.sheild_wire_margin;
    SPINBOX_SetValue( hItem, t);
    SPINBOX_SetStep(hItem, calc_step(t));

    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_2);
    SPINBOX_SetRange( hItem, 1, 999 );
    t = nvrom_data.sheild_sheild_margin;
    SPINBOX_SetValue( hItem, t);
    SPINBOX_SetStep(hItem, calc_step(t));

    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_3);
    SPINBOX_SetRange( hItem, 1, 1000 );
    SPINBOX_SetValue( hItem, nvrom_data.adc_delay );
    SPINBOX_SetStep( hItem, 50 );

    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_4);
    SPINBOX_SetRange( hItem, 1, 9999 );
    SPINBOX_SetValue( hItem, nvrom_data.wire_delay );
    SPINBOX_SetStep( hItem, 100 );

    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_5);
    SPINBOX_SetRange( hItem, 1, 1999 );
    SPINBOX_SetValue( hItem, nvrom_data.calib_add );

    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_6);
    SPINBOX_SetRange( hItem, 1, 19999 );
    SPINBOX_SetValue( hItem, nvrom_data.calib_mul );

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SPINBOX_0: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_1: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
    	  t = SPINBOX_GetValue(pMsg->hWinSrc);
    	  SPINBOX_SetStep(pMsg->hWinSrc, t / 10 + 1);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_2: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
    	  t = SPINBOX_GetValue(pMsg->hWinSrc);
    	  SPINBOX_SetStep(pMsg->hWinSrc, t / 10 + 1);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_3: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_4: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Touch Calibration'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
    	  context.send_cmd = CMD_REQ_CALIB;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Exit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
    	  context.send_cmd = CMD_EXIT_SETTINGS;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_5: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_6: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSettings
*/
WM_HWIN CreateSettings(void);
WM_HWIN CreateSettings(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
WM_HWIN hWinSettings;
void copy_settings(void){
	WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWinSettings, ID_CHECKBOX_0);
    nvrom_data.check_good = CHECKBOX_IsChecked(hItem);
    hItem = WM_GetDialogItem(hWinSettings, ID_SPINBOX_0);
	nvrom_data.wire_wire_margin = SPINBOX_GetValue(hItem);
    hItem = WM_GetDialogItem(hWinSettings, ID_SPINBOX_1);
	nvrom_data.sheild_wire_margin = SPINBOX_GetValue(hItem);
    hItem = WM_GetDialogItem(hWinSettings, ID_SPINBOX_2);
	nvrom_data.sheild_sheild_margin = SPINBOX_GetValue(hItem);
    hItem = WM_GetDialogItem(hWinSettings, ID_SPINBOX_3);
	nvrom_data.adc_delay = SPINBOX_GetValue(hItem);
    hItem = WM_GetDialogItem(hWinSettings, ID_SPINBOX_4);
	nvrom_data.wire_delay = SPINBOX_GetValue(hItem);
    hItem = WM_GetDialogItem(hWinSettings, ID_SPINBOX_5);
	nvrom_data.calib_add = SPINBOX_GetValue(hItem);
    hItem = WM_GetDialogItem(hWinSettings, ID_SPINBOX_6);
	nvrom_data.calib_mul = SPINBOX_GetValue(hItem);

}
// USER END

/*************************** End of file ****************************/
